### ISSUE TITLE
Frontend Roadmap

### ISSUE THREAD

**Issue by coyotte508** [liberodark/ODrive#4]
- [x] Minimize to tray icon
- [x] Notifications when files are remotely changed
- [x] Change tray icon when connection is lost
- [x] Change folder functionality
- [ ] Possibility to close account
